/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type CreateAccountStatus200 = {
    name: string;
};

export type CreateAccountBody = {
    name: string;
};

export type CreateAccountOptions = {
    body: CreateAccountBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateAccountResponses = {
    "200": CreateAccountStatus200;
};

/**
 * @description Union of all possible responses
*/
export type CreateAccountResponse = CreateAccountStatus200;
