/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateAccountStatus201 = null;

/**
 * @example {"error":"CONFLICT","message":"E-mail already registered","statusCode":409}
 * @type object
 */
export type CreateAccountStatus409 = {
    error: string;
    message: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    statusCode: number;
};

/**
 * @example {"name":"Arthur Reis","email":"arthur@example.com","password":"senha-forte-123","showOnWall":true}
 * @type object
 */
export type CreateAccountBody = {
    /**
     * @minLength 1
     * @type string
     */
    name: string;
    /**
     * @description
     * Format: `email`
     * @type string
     */
    email: string;
    /**
     * @minLength 8
     * @type string
     */
    password: string;
    showOnWall: boolean;
};

export type CreateAccountOptions = {
    body: CreateAccountBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type CreateAccountResponses = {
    '201': CreateAccountStatus201;
    '409': CreateAccountStatus409;
};

/**
 * @description Union of all possible responses
 */
export type CreateAccountResponse =
    CreateAccountStatus201 | CreateAccountStatus409;
