/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example {"count":42}
 * @type object
 */
export type GetMembersCountStatus200 = {
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    count: number;
};

export type GetMembersCountOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMembersCountResponses = {
    '200': GetMembersCountStatus200;
};

/**
 * @description Union of all possible responses
 */
export type GetMembersCountResponse = GetMembersCountStatus200;
