/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example [{"id":"b3f1c9de-6e2a-4c3a-9f9b-6b5e2b6a2f2e","name":"Arthur Reis","memberNumber":42,"joinedAt":"2026-09-18T12:00:00.000Z"}]
 * @type array
 */
export type ListMembersStatus200 = {
    id: string;
    name: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    memberNumber: number;
    /**
     * @description
     * Format: `date-time`
     * @type string
     */
    joinedAt: string;
}[];

/**
 * @example {"error":"UNAUTHORIZED","message":"Unauthorized","statusCode":401}
 * @type object
 */
export type ListMembersStatus401 = {
    error: string;
    message: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    statusCode: number;
};

export type ListMembersOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type ListMembersResponses = {
    '200': ListMembersStatus200;
    '401': ListMembersStatus401;
};

/**
 * @description Union of all possible responses
 */
export type ListMembersResponse = ListMembersStatus200 | ListMembersStatus401;
