/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @example {"id":"b3f1c9de-6e2a-4c3a-9f9b-6b5e2b6a2f2e","name":"Arthur Reis","email":"arthur@example.com","memberNumber":42,"joinedAt":"2026-09-18T12:00:00.000Z","showWall":true}
 * @type object
*/
export type ProfileStatus200 = {
    id: string;
    name: string;
    email: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
    */
    memberNumber: number;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    joinedAt: string;
    showWall: boolean;
};

/**
 * @example {"error":"UNAUTHORIZED","message":"Unauthorized","statusCode":401}
 * @type object
*/
export type ProfileStatus401 = {
    error: string;
    message: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
    */
    statusCode: number;
};

export type ProfileOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type ProfileResponses = {
    "200": ProfileStatus200;
    "401": ProfileStatus401;
};

/**
 * @description Union of all possible responses
*/
export type ProfileResponse = (ProfileStatus200 | ProfileStatus401);
