/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SignInStatus200 = null;

/**
 * @example {"error":"UNAUTHORIZED","message":"Invalid email or password","statusCode":401}
 * @type object
 */
export type SignInStatus401 = {
    error: string;
    message: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    statusCode: number;
};

/**
 * @example {"email":"arthur@example.com","password":"senha-forte-123"}
 * @type object
 */
export type SignInBody = {
    /**
     * @description
     * Format: `email`
     * @type string
     */
    email: string;
    /**
     * @minLength 1
     * @type string
     */
    password: string;
};

export type SignInOptions = {
    body: SignInBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type SignInResponses = {
    '200': SignInStatus200;
    '401': SignInStatus401;
};

/**
 * @description Union of all possible responses
 */
export type SignInResponse = SignInStatus200 | SignInStatus401;
