/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SignOutStatus200 = null;

export type SignOutOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type SignOutResponses = {
    '200': SignOutStatus200;
};

/**
 * @description Union of all possible responses
 */
export type SignOutResponse = SignOutStatus200;
