/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const createAccountStatus200Schema = z.object({
  name: z.string(),
}).strict()

export const createAccountResponseSchema = createAccountStatus200Schema

export const createAccountBodySchema = z.object({
  name: z.string(),
})
