/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const createAccountStatus201Schema = z.null();

export const createAccountStatus409Schema = z
    .object({
        error: z.string(),
        message: z.string(),
        statusCode: z.int().min(-9007199254740991).max(9007199254740991),
    })
    .strict()
    .meta({ examples: [{}] });

export const createAccountResponseSchema = createAccountStatus201Schema;

export const createAccountErrorSchema = createAccountStatus409Schema;

export const createAccountBodySchema = z
    .object({
        name: z.string().min(1),
        email: z.email(),
        password: z.string().min(8),
        showOnWall: z.boolean(),
    })
    .meta({ examples: [{}] });
