/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const getMembersCountStatus200Schema = z
    .object({
        count: z.int().min(-9007199254740991).max(9007199254740991),
    })
    .strict()
    .meta({ examples: [{}] });

export const getMembersCountResponseSchema = getMembersCountStatus200Schema;
