/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const listMembersStatus200Schema = z.array(z.object({
  id: z.string(),
  name: z.string(),
  memberNumber: z.int().min(-9007199254740991).max(9007199254740991),
  joinedAt: z.iso.datetime(),
}).strict()).meta({ examples: [[{"id":"b3f1c9de-6e2a-4c3a-9f9b-6b5e2b6a2f2e","name":"Arthur Reis","memberNumber":42,"joinedAt":"2026-09-18T12:00:00.000Z"}]] })

export const listMembersStatus401Schema = z.object({
  error: z.string(),
  message: z.string(),
  statusCode: z.int().min(-9007199254740991).max(9007199254740991),
}).strict().meta({ examples: [{}] })

export const listMembersResponseSchema = listMembersStatus200Schema

export const listMembersErrorSchema = listMembersStatus401Schema
