/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const profileStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  memberNumber: z.int().min(-9007199254740991).max(9007199254740991),
  joinedAt: z.iso.datetime(),
  showWall: z.boolean(),
}).strict().meta({ examples: [{}] })

export const profileStatus401Schema = z.object({
  error: z.string(),
  message: z.string(),
  statusCode: z.int().min(-9007199254740991).max(9007199254740991),
}).strict().meta({ examples: [{}] })

export const profileResponseSchema = profileStatus200Schema

export const profileErrorSchema = profileStatus401Schema
