/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const signOutStatus200Schema = z.null();

export const signOutResponseSchema = signOutStatus200Schema;
