/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const signInStatus200Schema = z.null();

export const signInStatus401Schema = z
    .object({
        error: z.string(),
        message: z.string(),
        statusCode: z.int().min(-9007199254740991).max(9007199254740991),
    })
    .strict()
    .meta({ examples: [{}] });

export const signInResponseSchema = signInStatus200Schema;

export const signInErrorSchema = signInStatus401Schema;

export const signInBodySchema = z
    .object({
        email: z.email(),
        password: z.string().min(1),
    })
    .meta({ examples: [{}] });
