/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const signInStatus200Schema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  memberNumber: z.int().min(-9007199254740991).max(9007199254740991),
  joinedAt: z.iso.datetime(),
  showWall: z.boolean(),
}).strict().meta({ examples: [{}] })

export const signInStatus401Schema = z.object({
  error: z.string(),
  message: z.string(),
  statusCode: z.int().min(-9007199254740991).max(9007199254740991),
}).strict().meta({ examples: [{}] })

export const signInResponseSchema = signInStatus200Schema

export const signInErrorSchema = signInStatus401Schema

export const signInBodySchema = z.object({
  email: z.email(),
  password: z.string().min(1),
}).meta({ examples: [{}] })
