/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AppLayoutRouteImport } from './routes/app/layout'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/_sign-in/index'
import { Route as AuthCreateAccountIndexRouteImport } from './routes/_auth/create-account/index'
import { Route as AppWelcomeIndexRouteImport } from './routes/app/_welcome/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_sign-in/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthCreateAccountIndexRoute = AuthCreateAccountIndexRouteImport.update({
  id: '/create-account/',
  path: '/create-account/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppWelcomeIndexRoute = AppWelcomeIndexRouteImport.update({
  id: '/_welcome/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthSignInIndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/create-account/': typeof AuthCreateAccountIndexRoute
  '/app/': typeof AppWelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthSignInIndexRoute
  '/create-account': typeof AuthCreateAccountIndexRoute
  '/app': typeof AppWelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/app': typeof AppLayoutRouteWithChildren
  '/_auth/_sign-in/': typeof AuthSignInIndexRoute
  '/_auth/create-account/': typeof AuthCreateAccountIndexRoute
  '/app/_welcome/': typeof AppWelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/create-account/' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-account' | '/app'
  id:
    | '__root__'
    | '/_auth'
    | '/app'
    | '/_auth/_sign-in/'
    | '/_auth/create-account/'
    | '/app/_welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_sign-in/': {
      id: '/_auth/_sign-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/create-account/': {
      id: '/_auth/create-account/'
      path: '/create-account'
      fullPath: '/create-account/'
      preLoaderRoute: typeof AuthCreateAccountIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/_welcome/': {
      id: '/app/_welcome/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppWelcomeIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthCreateAccountIndexRoute: typeof AuthCreateAccountIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthCreateAccountIndexRoute: AuthCreateAccountIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AppLayoutRouteChildren {
  AppWelcomeIndexRoute: typeof AppWelcomeIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppWelcomeIndexRoute: AppWelcomeIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
