/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, Unwrappable, RequestResult } from '../.kubb/client';
import type {
    CreateAccountOptions,
    CreateAccountResponses,
} from '../types/CreateAccount';
import { client, withUnwrap } from '../.kubb/client';

/**
 * @description Registers a new account and sends a welcome email.
 * {@link /create-account}
 */
export function createAccount<ThrowOnError extends boolean = true>(
    options: Options<CreateAccountOptions, ThrowOnError>,
): Unwrappable<RequestResult<CreateAccountResponses, ThrowOnError>> {
    const { client: request = client, ...config } = options;

    return withUnwrap(
        request({
            method: 'POST',
            url: '/create-account',
            ...config,
        }) as Promise<RequestResult<CreateAccountResponses, ThrowOnError>>,
    );
}
