/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, Unwrappable, RequestResult } from '../.kubb/client';
import type {
    GetMembersCountOptions,
    GetMembersCountResponses,
} from '../types/GetMembersCount';
import { client, withUnwrap } from '../.kubb/client';

/**
 * @description Returns the total number of registered accounts. Public.
 * {@link /members/count}
 */
export function getMembersCount<ThrowOnError extends boolean = true>(
    options: Options<GetMembersCountOptions, ThrowOnError> = {},
): Unwrappable<RequestResult<GetMembersCountResponses, ThrowOnError>> {
    const { client: request = client, ...config } = options;

    return withUnwrap(
        request({ method: 'GET', url: '/members/count', ...config }) as Promise<
            RequestResult<GetMembersCountResponses, ThrowOnError>
        >,
    );
}
