/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { ListMembersOptions, ListMembersResponses } from '../types/ListMembers'
import { client, withUnwrap } from '../.kubb/client'

/**
 * @description Lista os membros que optaram por aparecer no mural, ordenados pela numeração de associação. Requer sessão autenticada.
 * {@link /members}
 */
export function listMembers<ThrowOnError extends boolean = true>(options: Options<ListMembersOptions, ThrowOnError> = {}): Unwrappable<RequestResult<ListMembersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/members', ...config }) as Promise<RequestResult<ListMembersResponses, ThrowOnError>>)
}
