/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, Unwrappable, RequestResult } from '../.kubb/client';
import type { ProfileOptions, ProfileResponses } from '../types/Profile';
import { client, withUnwrap } from '../.kubb/client';

/**
 * @description Returns the signed-in user's profile.
 * {@link /profile}
 */
export function profile<ThrowOnError extends boolean = true>(
    options: Options<ProfileOptions, ThrowOnError> = {},
): Unwrappable<RequestResult<ProfileResponses, ThrowOnError>> {
    const { client: request = client, ...config } = options;

    return withUnwrap(
        request({
            method: 'GET',
            url: '/profile',
            security: [
                { type: 'apiKey', name: 'auth-lab-session', in: 'cookie' },
            ],
            ...config,
        }) as Promise<RequestResult<ProfileResponses, ThrowOnError>>,
    );
}
