/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, Unwrappable, RequestResult } from '../.kubb/client';
import type { SignInOptions, SignInResponses } from '../types/SignIn';
import { client, withUnwrap } from '../.kubb/client';

/**
 * @description Autentica um usuário com e-mail e senha e emite uma sessão via cookie httpOnly contendo um JWT.
 * {@link /sign-in}
 */
export function signIn<ThrowOnError extends boolean = true>(
    options: Options<SignInOptions, ThrowOnError>,
): Unwrappable<RequestResult<SignInResponses, ThrowOnError>> {
    const { client: request = client, ...config } = options;

    return withUnwrap(
        request({ method: 'POST', url: '/sign-in', ...config }) as Promise<
            RequestResult<SignInResponses, ThrowOnError>
        >,
    );
}
