/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, Unwrappable, RequestResult } from '../.kubb/client';
import type { SignOutOptions, SignOutResponses } from '../types/SignOut';
import { client, withUnwrap } from '../.kubb/client';

/**
 * @description Signs out by clearing the session cookie.
 * {@link /sign-out}
 */
export function signOut<ThrowOnError extends boolean = true>(
    options: Options<SignOutOptions, ThrowOnError> = {},
): Unwrappable<RequestResult<SignOutResponses, ThrowOnError>> {
    const { client: request = client, ...config } = options;

    return withUnwrap(
        request({ method: 'POST', url: '/sign-out', ...config }) as Promise<
            RequestResult<SignOutResponses, ThrowOnError>
        >,
    );
}
