/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
    UseMutationOptions,
    UseMutationResult,
    QueryClient,
} from '@tanstack/react-query';
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client';
import type {
    CreateAccountOptions,
    CreateAccountStatus201,
    CreateAccountStatus409,
} from '../types/CreateAccount';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { createAccount } from '../clients/createAccount';

export const createAccountMutationKey = () =>
    [{ url: '/create-account' }] as const;

export function createAccountMutationOptions<TContext = unknown>(
    config: Partial<
        Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
    > = {},
) {
    const mutationKey = createAccountMutationKey();
    return mutationOptions<
        CreateAccountStatus201,
        ResponseErrorConfig<CreateAccountStatus409>,
        CreateAccountOptions,
        TContext
    >({
        mutationKey,
        mutationFn: async ({ body }) => {
            return createAccount({
                ...config,
                body,
                throwOnError: true,
            }).unwrap();
        },
    });
}

/**
 * @description Registers a new account and sends a welcome email.
 * {@link /create-account}
 */
export function useCreateAccount<TContext>(
    options: {
        mutation?: UseMutationOptions<
            CreateAccountStatus201,
            ResponseErrorConfig<CreateAccountStatus409>,
            CreateAccountOptions,
            TContext
        > & { client?: QueryClient };
        client?: Partial<
            Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
        >;
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...mutationOptions } = mutation;
    const mutationKey =
        mutationOptions.mutationKey ?? createAccountMutationKey();

    const baseOptions = createAccountMutationOptions(
        config,
    ) as UseMutationOptions<
        CreateAccountStatus201,
        ResponseErrorConfig<CreateAccountStatus409>,
        CreateAccountOptions,
        TContext
    >;

    return useMutation<
        CreateAccountStatus201,
        ResponseErrorConfig<CreateAccountStatus409>,
        CreateAccountOptions,
        TContext
    >(
        {
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    ) as UseMutationResult<
        CreateAccountStatus201,
        ResponseErrorConfig<CreateAccountStatus409>,
        CreateAccountOptions,
        TContext
    >;
}
