/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { CreateAccountOptions, CreateAccountStatus200 } from '../types/CreateAccount'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { createAccount } from '../clients/createAccount'

export const createAccountMutationKey = () => [{ url: '/create-account' }] as const

export function createAccountMutationOptions<TContext = unknown>(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const mutationKey = createAccountMutationKey()
  return mutationOptions<CreateAccountStatus200, ResponseErrorConfig<Error>, CreateAccountOptions, TContext>({
    mutationKey,
    mutationFn: async({ body }) => {
      return createAccount({ ...config, body, throwOnError: true }).unwrap()
    },
  })
}

/**
 * {@link /create-account}
 */
export function useCreateAccount<TContext>(options: {
  mutation?: UseMutationOptions<CreateAccountStatus200, ResponseErrorConfig<Error>, CreateAccountOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createAccountMutationKey()

  const baseOptions = createAccountMutationOptions(config) as UseMutationOptions<CreateAccountStatus200, ResponseErrorConfig<Error>, CreateAccountOptions, TContext>

  return useMutation<CreateAccountStatus200, ResponseErrorConfig<Error>, CreateAccountOptions, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateAccountStatus200, ResponseErrorConfig<Error>, CreateAccountOptions, TContext>
}
