/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
    QueryKey,
    QueryClient,
    QueryObserverOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client';
import type { GetMembersCountStatus200 } from '../types/GetMembersCount';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getMembersCount } from '../clients/getMembersCount';

export const getMembersCountQueryKey = () =>
    [{ url: '/members/count' }] as const;

type GetMembersCountQueryKey = ReturnType<typeof getMembersCountQueryKey>;

export function getMembersCountQueryOptions(
    config: Partial<
        Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
    > = {},
) {
    const queryKey = getMembersCountQueryKey();
    return queryOptions<
        GetMembersCountStatus200,
        ResponseErrorConfig<Error>,
        GetMembersCountStatus200,
        typeof queryKey
    >({
        queryKey,
        queryFn: async ({ signal }) => {
            return getMembersCount({
                ...config,
                signal: config.signal ?? signal,
                throwOnError: true,
            }).unwrap();
        },
    });
}

/**
 * @description Retorna o total de contas cadastradas no AuthLab. Pública, usada na página de autenticação.
 * {@link /members/count}
 */
export function useGetMembersCount<
    TData = GetMembersCountStatus200,
    TQueryData = GetMembersCountStatus200,
    TQueryKey extends QueryKey = GetMembersCountQueryKey,
>(
    options: {
        query?: Partial<
            QueryObserverOptions<
                GetMembersCountStatus200,
                ResponseErrorConfig<Error>,
                TData,
                TQueryData,
                TQueryKey
            >
        > & { client?: QueryClient };
        client?: Partial<
            Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
        >;
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? getMembersCountQueryKey();

    const queryResult = useQuery(
        {
            ...getMembersCountQueryOptions(config),
            ...resolvedOptions,
            queryKey,
        } as unknown as QueryObserverOptions,
        queryClient,
    ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
        queryKey: TQueryKey;
    };

    queryResult.queryKey = queryKey as TQueryKey;

    return queryResult;
}
