/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListMembersStatus200, ListMembersStatus401 } from '../types/ListMembers'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { listMembers } from '../clients/listMembers'

export const listMembersSuspenseQueryKey = () => [{ url: '/members' }] as const

type ListMembersSuspenseQueryKey = ReturnType<typeof listMembersSuspenseQueryKey>

export function listMembersSuspenseQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listMembersSuspenseQueryKey()
  return queryOptions<ListMembersStatus200, ResponseErrorConfig<ListMembersStatus401>, ListMembersStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      return listMembers({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * @description Lista os membros que optaram por aparecer no mural, ordenados pela numeração de associação. Requer sessão autenticada.
 * {@link /members}
 */
export function useListMembersSuspense<TData = ListMembersStatus200, TQueryKey extends QueryKey = ListMembersSuspenseQueryKey>(options: {
  query?: Partial<UseSuspenseQueryOptions<ListMembersStatus200, ResponseErrorConfig<ListMembersStatus401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listMembersSuspenseQueryKey()

  const queryResult = useSuspenseQuery({
   ...listMembersSuspenseQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListMembersStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
