/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ListMembersStatus200, ListMembersStatus401 } from '../types/ListMembers'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { listMembers } from '../clients/listMembers'

export const listMembersQueryKey = () => [{ url: '/members' }] as const

type ListMembersQueryKey = ReturnType<typeof listMembersQueryKey>

export function listMembersQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = listMembersQueryKey()
  return queryOptions<ListMembersStatus200, ResponseErrorConfig<ListMembersStatus401>, ListMembersStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      return listMembers({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * @description Lista os membros que optaram por aparecer no mural, ordenados pela numeração de associação. Requer sessão autenticada.
 * {@link /members}
 */
export function useListMembers<TData = ListMembersStatus200, TQueryData = ListMembersStatus200, TQueryKey extends QueryKey = ListMembersQueryKey>(options: {
  query?: Partial<QueryObserverOptions<ListMembersStatus200, ResponseErrorConfig<ListMembersStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listMembersQueryKey()

  const queryResult = useQuery({
   ...listMembersQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<ListMembersStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
