/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { ProfileStatus200, ProfileStatus401 } from '../types/Profile'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { profile } from '../clients/profile'

export const profileSuspenseQueryKey = () => [{ url: '/profile' }] as const

type ProfileSuspenseQueryKey = ReturnType<typeof profileSuspenseQueryKey>

export function profileSuspenseQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = profileSuspenseQueryKey()
  return queryOptions<ProfileStatus200, ResponseErrorConfig<ProfileStatus401>, ProfileStatus200, typeof queryKey>({
   queryKey,
   queryFn: async ({ signal }) => {
      return profile({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * @description Retorna os dados do usuário autenticado a partir da sessão do cookie.
 * {@link /profile}
 */
export function useProfileSuspense<TData = ProfileStatus200, TQueryKey extends QueryKey = ProfileSuspenseQueryKey>(options: {
  query?: Partial<UseSuspenseQueryOptions<ProfileStatus200, ResponseErrorConfig<ProfileStatus401>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? profileSuspenseQueryKey()

  const queryResult = useSuspenseQuery({
   ...profileSuspenseQueryOptions(config),
   ...resolvedOptions,
   queryKey,
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ProfileStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
