/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
    QueryKey,
    QueryClient,
    QueryObserverOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client';
import type { ProfileStatus200, ProfileStatus401 } from '../types/Profile';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { profile } from '../clients/profile';

export const profileQueryKey = () => [{ url: '/profile' }] as const;

type ProfileQueryKey = ReturnType<typeof profileQueryKey>;

export function profileQueryOptions(
    config: Partial<
        Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
    > = {},
) {
    const queryKey = profileQueryKey();
    return queryOptions<
        ProfileStatus200,
        ResponseErrorConfig<ProfileStatus401>,
        ProfileStatus200,
        typeof queryKey
    >({
        queryKey,
        queryFn: async ({ signal }) => {
            return profile({
                ...config,
                signal: config.signal ?? signal,
                throwOnError: true,
            }).unwrap();
        },
    });
}

/**
 * @description Returns the signed-in user's profile.
 * {@link /profile}
 */
export function useProfile<
    TData = ProfileStatus200,
    TQueryData = ProfileStatus200,
    TQueryKey extends QueryKey = ProfileQueryKey,
>(
    options: {
        query?: Partial<
            QueryObserverOptions<
                ProfileStatus200,
                ResponseErrorConfig<ProfileStatus401>,
                TData,
                TQueryData,
                TQueryKey
            >
        > & { client?: QueryClient };
        client?: Partial<
            Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
        >;
    } = {},
) {
    const { query: queryConfig = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...resolvedOptions } = queryConfig;
    const queryKey = resolvedOptions?.queryKey ?? profileQueryKey();

    const queryResult = useQuery(
        {
            ...profileQueryOptions(config),
            ...resolvedOptions,
            queryKey,
        } as unknown as QueryObserverOptions,
        queryClient,
    ) as UseQueryResult<TData, ResponseErrorConfig<ProfileStatus401>> & {
        queryKey: TQueryKey;
    };

    queryResult.queryKey = queryKey as TQueryKey;

    return queryResult;
}
