/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
    UseMutationOptions,
    UseMutationResult,
    QueryClient,
} from '@tanstack/react-query';
import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client';
import type {
    SignInOptions,
    SignInStatus200,
    SignInStatus401,
} from '../types/SignIn';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import { signIn } from '../clients/signIn';

export const signInMutationKey = () => [{ url: '/sign-in' }] as const;

export function signInMutationOptions<TContext = unknown>(
    config: Partial<
        Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
    > = {},
) {
    const mutationKey = signInMutationKey();
    return mutationOptions<
        SignInStatus200,
        ResponseErrorConfig<SignInStatus401>,
        SignInOptions,
        TContext
    >({
        mutationKey,
        mutationFn: async ({ body }) => {
            return signIn({ ...config, body, throwOnError: true }).unwrap();
        },
    });
}

/**
 * @description Signs in with email and password, starting a session cookie.
 * {@link /sign-in}
 */
export function useSignIn<TContext>(
    options: {
        mutation?: UseMutationOptions<
            SignInStatus200,
            ResponseErrorConfig<SignInStatus401>,
            SignInOptions,
            TContext
        > & { client?: QueryClient };
        client?: Partial<
            Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>
        >;
    } = {},
) {
    const { mutation = {}, client: config = {} } = options ?? {};
    const { client: queryClient, ...mutationOptions } = mutation;
    const mutationKey = mutationOptions.mutationKey ?? signInMutationKey();

    const baseOptions = signInMutationOptions(config) as UseMutationOptions<
        SignInStatus200,
        ResponseErrorConfig<SignInStatus401>,
        SignInOptions,
        TContext
    >;

    return useMutation<
        SignInStatus200,
        ResponseErrorConfig<SignInStatus401>,
        SignInOptions,
        TContext
    >(
        {
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
        },
        queryClient,
    ) as UseMutationResult<
        SignInStatus200,
        ResponseErrorConfig<SignInStatus401>,
        SignInOptions,
        TContext
    >;
}
